opensearch-project/opensearch-ruby

- MAINTAINERS.md
- opensearch-api/lib/opensearch/api/version.rb
- opensearch-api/opensearch-api.gemspec
- opensearch-dsl/lib/opensearch/dsl/version.rb
- opensearch-dsl/opensearch-dsl.gemspec
- opensearch-ruby.iml
- opensearch-transport/lib/opensearch/transport/version.rb
- opensearch-transport/opensearch-transport.gemspec
- opensearch/opensearch.gemspec
> Updated maintainers rubygem

- .github/workflows/links.yml
- README.md
- opensearch-dsl/README.md
Signed-off-by: jayeshathila <sharma.jayesh52@gmail.com>
Add client connection code sample in readme
> Add client connection code sample in readme

- .github/workflows/main.yml
Consider running workflow for PR and push on
branch 1.0
> Include 1.0 branch for workflow

- .github/actions/opensearch/action.yml
- .github/actions/opensearch/run.sh
- .github/workflows/main.yml
- opensearch/Rakefile
- opensearch/spec/integration/security_disabled/client_integration_spec.rb
- opensearch/spec/integration/security_disabled/validation_integration_spec.rb
- opensearch/spec/integration/security_enabled/client_integration_spec.rb
- opensearch/spec/integration/security_enabled/validation_integration_spec.rb
Signed-off-by: jayeshathila <sharma.jayesh52@gmail.com>
Add integration test for security plugin enabled
https://github.com/opensearch-project/opensearch-ruby/issues/31
> Add integration test for security plugin enabled

- .github/workflows/backport.yml
- .github/workflows/delete_backport_branch.yml
- MAINTAINERS.md
Adding auto backport functionality with auto delete for the backport branches. 
Closes #58 
> Adding auto backport functionality

- .github/workflows/compatibility.yml
- COMPATIBILITY.md
- opensearch-api/lib/opensearch/api/utils.rb
- opensearch-api/spec/opensearch/api/utils_spec.rb
Adding new OpenSearch versions and updating the compatibility matrix.
> Adding new OpenSearch versions and updating compatibility matrix

- COMPATIBILITY.md
- opensearch-api/lib/opensearch/api/version.rb
- opensearch/lib/opensearch/version.rb
- opensearch/opensearch.gemspec
> Bumping version to 2.0.2

- COMPATIBILITY.md
- opensearch-api/lib/opensearch/api/version.rb
- opensearch/lib/opensearch/version.rb
- opensearch/opensearch.gemspec
(cherry picked from commit da00f4b151018151ebe577f4c35a27240931b130)
Backport #83 to 2.0
> Bumping version to 2.0.2 (#83)

- .github/workflows/changelog_verifier.yml
> Exclude dependabot from changelog-enforcer

- CHANGELOG.md
- Gemfile
- README.md
- release/build.sh
> Updated release script in preparation for opensearch-aws-sigv4 release

- .github/CODEOWNERS
- CHANGELOG.md
- MAINTAINERS.md
Signed-off-by: Harsha Vamsi Kalluri <harshavamsi096@gmail.com>
Adding @harshavamsi to maintainers.
> Adding @harshavamsi to maintainers

- .github/workflows/release_drafter.yml
- CHANGELOG.md
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
Adds the missing token permissions required to grab the secrets.
> Add token permissions

- .github/workflows/release_drafter.yml
- CHANGELOG.md
Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
The token needs contents to be writable for release to be created. Ref: https://github.com/softprops/action-gh-release/issues/236#issuecomment-1150530128
> Fix token permissions

- CHANGELOG.md
- opensearch-dsl/lib/opensearch/dsl/version.rb
- opensearch-transport/lib/opensearch/transport/version.rb
> Version bump for dsl and transport in preparation for release

- .github/workflows/test-unreleased.yml
Reduce workflows runtime
closes https://github.com/opensearch-project/opensearch-ruby/issues/144
> Caching OpenSearch builds

- .github/workflows/test-unreleased.yml
- opensearch-aws-sigv4/CHANGELOG.md
- opensearch-aws-sigv4/lib/opensearch-aws-sigv4.rb
- opensearch-aws-sigv4/lib/opensearch-aws-sigv4/version.rb
> Added Sigv4 Debug Logging

- opensearch-api/CHANGELOG.md
- opensearch-api/lib/opensearch/api/version.rb
Bumped opensearch-api to version 2.2.0 in preparation for release
> Bumped opensearch-api to version 2.2.0

- CHANGELOG.md
- COMPATIBILITY.md
- README.md
- UPGRADING.md
- lib/opensearch/version.rb
> Version bump/3.0.0

- jenkins/release.JenkinsFile
> Bumped Jenkins to 5.7.1

- CHANGELOG.md
- lib/opensearch/version.rb
> Bumped Version 3.0.1

- CHANGELOG.md
- lib/opensearch/version.rb
> 3.1.0 Version Bump

- USER_GUIDE.md
While here, add syntax highlighting.
n/a
> Add missing quotes in user documentation

- CHANGELOG.md
- lib/opensearch/version.rb
> Bumped Version to 3.2.0

- CHANGELOG.md
https://github.com/opensearch-project/opensearch-ruby/issues/232
> Updated CHANGELOG.md to release 3.2.0 again

- .github/CODEOWNERS
- .github/workflows/backport.yml
- MAINTAINERS.md
> Added Earlopain to maintainers list

- CHANGELOG.md
- lib/opensearch/version.rb
> Bump version to 3.4.0

- lib/opensearch/version.rb
> Version bump: 4.0.0-beta.1

- .github/CODEOWNERS
- MAINTAINERS.md
> Moved jayeshathila to Emeritus

- CHANGELOG.md
- DEVELOPER_GUIDE.md
- USER_GUIDE.md
- lib/opensearch/transport/client.rb
- lib/opensearch/version.rb
- spec/opensearch/client/integration/security_enabled/client_integration_spec.rb
- spec/opensearch/client/unit/request_signer_spec.rb
Prereq for https://github.com/opensearch-project/opensearch-ruby-aws-sigv4/issues/50
> Added ability to sign requests.

- .github/workflows/main.yml
- Gemfile
There are two failures on 9.4 which I am not sure what they are about. Maybe this will get rid of them
_Describe what this change achieves._
> Test against jruby-10
