.gitignore
release/build.sh

This script will build following gems
1. opensearch
2. opensearch-api
3. opensearch-transport
4. opensearch-dsl
and will be moved inside dist folder
#23 

Add script to build gems

---

opensearch-api/README.md
opensearch-transport/README.md
opensearch/README.md

Remove place holder link at README file. Will add documentation link later.
#18 

Remove place holder link at README file

---

.github/workflows/main.yml
README.md
opensearch-api/Gemfile
opensearch-dsl/Gemfile
opensearch-transport/Gemfile
opensearch-transport/opensearch-transport.gemspec
opensearch/README.md
opensearch/opensearch.gemspec

Since gem name opensearch is taken, update name to
opensearch-ruby to avoid conflict.
#23  

Update gem name to opensearch-ruby

---

.github/workflows/main.yml
README.md
opensearch-api/Gemfile
opensearch-dsl/Gemfile
opensearch-transport/Gemfile
opensearch-transport/opensearch-transport.gemspec
opensearch/README.md
opensearch/opensearch.gemspec

Back port https://github.com/opensearch-project/opensearch-ruby/pull/43 to 1.0 branch
#23  

Backport #43 to 1.0 branch

---

.github/workflows/main.yml
opensearch-api/README.md

Signed-off-by: Peter Goldstein <peter.m.goldstein@gmail.com>
Adds Ruby 3.1 to the CI matrix
Fixes a bug in the existing CI matrix.  Github Actions will truncate an unquoted 3.0 to 3, and thus pull in the latest Ruby 3 version for that entry in the matrix.  At this time that's Ruby 3.1.1, which is not what's intended.  Adding quotes to the 3.0 resolves this issue.

Add Ruby 3.1 to the CI matrix

---

opensearch-api/README.md

Signed-off-by: Jayesh Hathila <jayehh@amazon.com>
Removing broken link from Readme. Will add back once we have correct doc in place.
https://github.com/opensearch-project/opensearch-ruby/issues/53

Remove broken link from Readme

---

.github/workflows/compatibility.yml
.github/workflows/main.yml
COMPATIBILITY.md

Adding support to run tests against multiple versions of OpenSearch in the CI. I separated out the `compatibility.yml` since the matrix was becoming huge in the `main.yml` with multiple ruby versions.
#56 

Add support to test against multiple versions of OpenSearch

---

.github/workflows/compatibility.yml
COMPATIBILITY.md
opensearch-api/lib/opensearch/api/version.rb
opensearch-dsl/lib/opensearch/dsl/version.rb
opensearch-transport/lib/opensearch/transport/version.rb
opensearch/lib/opensearch/version.rb
opensearch/opensearch.gemspec
opensearch/spec/integration/security_disabled/validation_integration_spec.rb
opensearch/spec/unit/opensearch_product_validation_spec.rb

* Bump client version to 2.0.0.
* Add OpenSearch 2.0 to the test matrix.
#68 

Bump client version to 2.0 and add OpenSearch 2.0

---

opensearch-api/lib/opensearch/api/utils.rb
opensearch-api/opensearch-api.gemspec
opensearch-api/spec/opensearch/api/utils_spec.rb

Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>
According to https://github.com/brianmario/escape_utils, _EscapeUtils used to provide optimized escaping function to replace the slow methods provided by Ruby. Since Ruby 2.5, the various CGI escape methods have been severely optimized and most EscapeUtils methods became irrelevant and were deprecated._ 
It outputs a warning at runtime, too: https://github.com/opensearch-project/opensearch-ruby/runs/6942537657?check_suite_focus=true 
```
#__listify
EscapeUtils.escape_url is deprecated. Use CGI.escape instead, performance is similar
creates a list from a single value
```
For more information on following Developer …

Remove deprecated escape_utils.

---

opensearch/lib/opensearch.rb
profile/benchmarking.rb

Using `safe_load` instead of `load` for YAML.

Use safe_load instead of load for yaml

---

opensearch-api/lib/opensearch/api/utils.rb
opensearch-api/opensearch-api.gemspec
opensearch-api/spec/opensearch/api/utils_spec.rb

Signed-off-by: Daniel (dB.) Doubrovkine <dblock@amazon.com>
(cherry picked from commit 7ab1830c16f36cc090a8bd1fe42500ecdc3de283)
Backport #74 to 2.0

Remove deprecated escape_utils. (#74)

---

COMPATIBILITY.md
opensearch-api/lib/opensearch/api/version.rb
opensearch/lib/opensearch/version.rb
opensearch/opensearch.gemspec

(cherry picked from commit 5f56db977a71bda3ef7cbcf4002b12f96a54bde6)
Backport #78 to 2.0

Bumping opensearch ruby gem version to 2.0.1 (#78)

---

.github/workflows/main.yml
opensearch-transport/Gemfile
opensearch-transport/README.md
opensearch-transport/lib/opensearch/transport/client.rb
opensearch-transport/opensearch-transport.gemspec
opensearch-transport/spec/spec_helper.rb
opensearch-transport/test/integration/transport_test.rb

- Support Faraday 1.x and 2.x in opensearch-transport.
- Made client autodetection not break if the detected HTTP client is
there but the associated Faraday adapter is not.
- Made the test setup require the referenced adapters.
- Made it more clear in the README that Faraday uses adapters.
[Fixes #59]
This makes it possible to use opensearch-transport with Faraday 1 or 2.
Closes [#59] for  opensearch-transport 2.x.

Faraday 2 support for opensearch-transport 2

---

opensearch-api/lib/opensearch/api/utils.rb
opensearch-api/opensearch-api.gemspec
opensearch-api/spec/opensearch/api/utils_spec.rb
opensearch-transport/spec/opensearch/transport/base_spec.rb
opensearch-transport/spec/opensearch/transport/client_spec.rb

Fixes tests in 1.x by backporting fixes from 2.0.x.

[Backport 1.x] Remove deprecated escape_utils, and test fixes

---

opensearch-transport/Gemfile
opensearch-transport/README.md
opensearch-transport/opensearch-transport.gemspec
opensearch-transport/spec/opensearch/transport/client_spec.rb
opensearch-transport/test/integration/transport_test.rb

Ruby 2.6 (and JRuby 9.3) works with faraday-typhoeus now. Gemfile restrictions and README adjusted accordingly. No app changes. Adjusted some Patron test restrictions which were hidden before because Faraday 2 wasn't being tested with JRuby, due to the old faraday-typhoeus version restriction.

Ruby 2.6 works with faraday-typhoeus now

---

opensearch-transport/lib/opensearch/transport/version.rb
opensearch/lib/opensearch/version.rb
opensearch/opensearch.gemspec

Bumping version to 1.0.1 for opensearch-transport.
#91 

Bumping version to 1.0.1 for opensearch-transport

---

opensearch-transport/lib/opensearch/transport/version.rb
opensearch/lib/opensearch/version.rb
opensearch/opensearch.gemspec

Bumping version to 2.0.1 for opensearch-transport.
#91 

Bumping version to 2.0.1 for opensearch-transport

---

.github/CODEOWNERS
ADMINS.md
MAINTAINERS.md

- Added @dblock, @VachaShah, and @nhtruong as maintainers.
- Updated CODEOWNERS to reflect the current maintainers.
- Updated MAINTAINERS.md to refer to opensearch-project's MAINTAINERS.md for consistency and avoid duplication.
- Updated ADMINS.md to refer to opensearch-project's ADMINS.md for consistency and avoid duplication.

Update Maintainers List

---

CHANGELOG.md
opensearch-dsl/opensearch-dsl.gemspec

Opensearch-DSL gem was using Mocha 1.x.x for its unit tests. Mocha has just released 2.0.0 which breaks some of the tests. This will lock mocha to 1.x.x for Opensearch-DSL

Fixed Mocha Dependency

---

.github/workflows/compatibility.yml
.github/workflows/main.yml
.github/workflows/test-unreleased.yml
CHANGELOG.md
Rakefile
opensearch-aws-sigv4/.gitignore
opensearch-aws-sigv4/Gemfile
opensearch-aws-sigv4/LICENSE
opensearch-aws-sigv4/README.md
opensearch-aws-sigv4/Rakefile
opensearch-aws-sigv4/bin/opensearch_ruby_console
opensearch-aws-sigv4/lib/opensearch-aws-sigv4.rb
opensearch-aws-sigv4/lib/opensearch-aws-sigv4/version.rb
opensearch-aws-sigv4/opensearch-aws-sigv4.gemspec
opensearch-aws-sigv4/spec/integration/sigv4_client_integration_spec.rb
opensearch-aws-sigv4/spec/spec_helper.rb
opensearch-aws-sigv4/spec/unit/sigv4_client_spec.rb

Added Sigv4 Client gem that is a wrapper of `opensearch-ruby` gem. This gem will sign every request with an AWS Sigv4 signature.
Closes https://github.com/opensearch-project/opensearch-ruby/issues/71

Aws Sigv4 Wrapper Gem for OpenSearch::Client

---

CHANGELOG.md
jenkins/release.JenkinsFile

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
The public certificate relative path was missing an `s` causing the cert to be not found. The new version fixes this bug.

Bump jenkins lib version

---

CHANGELOG.md
jenkins/release.JenkinsFile

Signed-off-by: Sayali Gaikawad <gaiksaya@amazon.com>
See https://github.com/opensearch-project/opensearch-build-libraries/pull/56 for details what the bug fix is about. 

Bump jenkins lib version to acommodate signed gem verification bug fix

---

CHANGELOG.md
opensearch-api/opensearch-api.gemspec
opensearch-dsl/opensearch-dsl.gemspec
opensearch-transport/opensearch-transport.gemspec

[CVE] Replaced `opensearch` with `opensearch-ruby` as dev dependency

---

opensearch-aws-sigv4/CHANGELOG.md
opensearch-aws-sigv4/lib/opensearch-aws-sigv4.rb
opensearch-aws-sigv4/opensearch-aws-sigv4.gemspec
opensearch-aws-sigv4/spec/unit/sigv4_client_spec.rb

Signed-off-by: Robin Roestenburg <robin.roestenburg@4me.com>
Fixes #130 by having the `opensearch-aws-sigv4` gem pass the signing headers to the request to verify / validate the OpenSearch distribution. 
When you do not use the AWS v4 signing, the behaviour of the `opensearch-ruby` gem is unchanged. The `verify_open_search` method is called without passing any headers (as before).
Closes #130. 

Sign validation request when using aws-sigv4 (#130)

---

opensearch-aws-sigv4/CHANGELOG.md
opensearch-aws-sigv4/README.md
opensearch-aws-sigv4/lib/opensearch-aws-sigv4.rb
opensearch-aws-sigv4/lib/opensearch-aws-sigv4/version.rb
opensearch-aws-sigv4/spec/unit/sigv4_client_spec.rb

Added Support for Amazon OpenSearch Serverless by skipping verification when `aoss` is detected as the service for Sigv4 Signer.
closes https://github.com/opensearch-project/opensearch-ruby/issues/131
closes #130 

Added Support for Amazon OpenSearch Serverless

---

.github/workflows/main.yml
opensearch-api/Rakefile
profile/benchmarking/benchmarking_tasks.rake
rake_tasks/test_tasks.rake

Ruby 3.2 has [been released](https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/)! Let's add it to the build matrix for confidence in compatibility.
The deprecated method `File.exists?` has been removed in Ruby 3.2. I've replaced occurrences with `File.exist?`.

CI: add Ruby 3.2 to the test matrix

---

.github/workflows/release_drafter.yml
RELEASING.md

This change retrieves the codeowner's list from .github/codeowners file and adds them as approvers for releasing opensearch-ruby
Here is a sample issue that is created when this workflow runs: https://github.com/gaiksaya/opensearch-ruby/issues/1
Once approved, the workflow continues to run as usual.
Note: This approval duration is subject to the broader 72 hours timeout for a workflow.
related https://github.com/opensearch-project/opensearch-build/issues/3111
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Add 2PR approval to release workflow

---

.github/workflows/test-unreleased.yml

Reduce `unreleased integration tests` workflow runtime
closes https://github.com/opensearch-project/opensearch-ruby/issues/144

Implemented Cache for Unreleased OpenSearch images

---

.github/license-header.txt
.rubocop.yml
CHANGELOG.md
guides/transport_options.md
lib/opensearch/api.rb
lib/opensearch/api/actions/remote_store/restore.rb
lib/opensearch/api/namespace/remote_store.rb
spec/opensearch/api/actions/remote_store/restore_spec.rb

All files, excepts `.rubocop.yml` and `CHANGELOG.md`, were generated by the [API generator](https://github.com/nhtruong/opensearch-ruby-api-generator) I'm working on. Once this has been merged, I'll follow up with a PR for the generator into this repo.

[CODE_GEN] Added `remote_store.restore` action

---

.github/build_gem.sh

The new name is clearer and matches the name used in `release_drafter` workflow
(forgot to do this after updating the workflow and the script to make it work with single-gem repo)

Renamed `build.sh` to `build_gem.sh`

---

jenkins/release.JenkinsFile

Looks like cert path changed from default `certs/` folder to .github.
Accommodating the same here in jenkins library.

Provide cert path to publishing library

---

jenkins/release.JenkinsFile

Provide the right path to certificate in the release Jenkins Job

Update the cert path to the publishing library in the release Jenkins job

---

.rubocop.yml
opensearch-ruby.gemspec

- Added Gemspec to the gem package for convenience when testing local gem with bundler
- Resolved open-ended dependencies for `multi_json`
- Updated `authors` and `email` fields to be in line with other OpenSearch gems.

Removed RubyGems MFA Opt-in clause

---

.github/workflows/compatibility.yml
.github/workflows/main.yml
.github/workflows/test-unreleased.yml
CHANGELOG.md
lib/opensearch.rb

Add a missing require to `opensearch/version`.
CI didn't catch this because `bundle exec rake` loads the gemspec file which requires the version on it's own. CI has no need for `bundle exec` since there will only ever be the exact gems installed so I have changed workflow to call rake on it's own.
#205

Missing require

---

CHANGELOG.md
lib/opensearch/transport/transport/response.rb
test/transport/unit/response_test.rb

Fixes an incompatibility with webmock since 3.19, where it started to freeze the response body for performance reasons
https://github.com/bblimke/webmock/pull/1033
https://github.com/bblimke/webmock/blob/v3.19.0/CHANGELOG.md#3190
When using code like the following, the response object tries to modify a frozen string:
```rb
def test_cluster_health_called
stub_request(:get, "http://opensearch/_cluster/health")
method_that_calls_out_to_cluster_health
end
```
This started happening since webmock version 3.19 because they applied the frozen string literal comment to their codebase. When not specifying a response body with `to_return(body: something)` the string will come from webmock itself and be frozen.
This changes the response to not modify the body when the string is frozen, avoiding this …

Don't modify the response if the body is frozen

---

CHANGELOG.md
opensearch-ruby.gemspec

* Add base64 to gemspec, which is no longer the default gem from Ruby 3.4.
* `opensearch-ruby` uses base64 gem in client.rb
```
❯ git grep "require 'base64'"
lib/opensearch/transport/client.rb:27:require 'base64'
```
* similar support in rails/rails: https://github.com/rails/rails/pull/48907
* bugs.ruby-lang: https://bugs.ruby-lang.org/issues/19776
* ruby/ruby: https://github.com/ruby/ruby/pull/8126

Add base64 to gemspec

---

.github/workflows/main.yml
CHANGELOG.md

Added with https://github.com/opensearch-project/opensearch-ruby/pull/178, should now be good to switch back.

Remove a todo in the testing workflow

---

.github/workflows/compatibility.yml
.github/workflows/main.yml
.github/workflows/test-unreleased.yml
CHANGELOG.md

Add the newly released ruby version to CI.
Question: JRuby is  being tested against 9.3 but 9.4 has been released [a while ago](https://www.jruby.org/2022/11/23/jruby-9-4-0-0.html). Should I also change this? If so, I'll do that after this PR has been merged.

Test against ruby 3.3

---

CHANGELOG.md
lib/opensearch/transport/client.rb
opensearch-ruby.gemspec
spec/opensearch/transport/client_spec.rb

https://github.com/opensearch-project/opensearch-ruby/pull/218 removed a warning in ruby 3.3 because of the base64 dependency. Since it's just a wrapper around the pack/unpack methods it's trivial to replace.
* https://github.com/rack/rack/pull/2110
* https://github.com/rubocop/rubocop/pull/12313
* https://github.com/newrelic/newrelic-ruby-agent/pull/2378
* https://github.com/lostisland/faraday/pull/1541

Remove dependency on the base64 gem

---

CHANGELOG.md
lib/opensearch/api/actions/search.rb
lib/opensearch/transport/transport/base.rb

closes https://github.com/opensearch-project/opensearch-ruby/issues/226
closes https://github.com/opensearch-project/opensearch-ruby/issues/224

Added search_pipeline

---

.github/actions/opensearch/run.sh
.github/workflows/compatibility.yml
.github/workflows/links.yml
.github/workflows/main.yml
CHANGELOG.md

Removes references to default admin credentials, which were removed in 2.12
Closes #222 

Remove reference to default credentials

---

CHANGELOG.md
lib/opensearch/dsl/search/options.rb
lib/opensearch/dsl/search/queries/match.rb

The removed `define_method` in `options.rb` just ensured that you are able to use `source` and `_source`, that's all this does. The other entries where this isn't a problem are simply overwritten, as you can see from the warnings. Just switch to handwriting this one special case.
The second change removes a `option_method :max_expansions` from `match.rb`. This previously appeared twice in the list and also caused a warning.
```
$ RUBYOPT=-w bundle exec irb
irb(main):001> require "opensearch-dsl"
opensearch-ruby/lib/opensearch/dsl/search/options.rb:59: warning: method redefined; discarding old fields
opensearch-ruby/lib/opensearch/dsl/search/options.rb:55: warning: previous definition of fields was here
opensearch-ruby/lib/opensearch/dsl/search/options.rb:59: warning: method redefined; …
```

Don't emit Ruby warnings when requiring `opensearch-dsl`

---

CHANGELOG.md
jenkins/release.JenkinsFile

As per https://github.com/opensearch-project/opensearch-build-libraries/blob/6d35e942e98e1acddd88633a2aa1bbe39ab5e002/vars/publishToRubyGems.groovy#L23 this is a supported config option.
The build failure is visible here: https://build.ci.opensearch.org/blue/organizations/jenkins/opensearch-ruby-gems-release/detail/opensearch-ruby-gems-release/31/pipeline
#232. I have manually confirmed that gem install with ruby 3.0 works. There are other warnings in the output relating to gem signing but I'm thinking that these are just errors happening down the road because of the the ruby version incompatibility.
For more information on following Developer Certificate of Origin and …

Fix release workflow

---

jenkins/release.JenkinsFile

Switch ruby version to 3.1.2 on release pipeline. There is no need to switch the docker image as, it is already pointing to most recent one. 
closes https://github.com/opensearch-project/opensearch-build/issues/4624

Switch ruby version to 3.1.2 on release pipeline

---

CHANGELOG.md
lib/opensearch/version.rb

Version Bump 3.3.0

---

CHANGELOG.md
lib/opensearch/dsl/search/queries/script_score.rb
spec/opensearch/dsl/search/queries/script_score_spec.rb

Script Score query was added to OpenSearch 2.9 and current query DSL does not support it.
This PR add script_score to query DSL.
https://github.com/opensearch-project/opensearch-ruby/issues/253

Add script_score to query DSL

---

.github/workflows/release_drafter.yml

Avoid timing out release tickets.

Lower the number of approvers required to do a release to 1.

---

.github/workflows/lint.yml
.github/workflows/main.yml
CHANGELOG.md

Note: This does a bit more than what is says in the title but it seems not worth to create individual PRs for that.
In https://github.com/opensearch-project/opensearch-ruby/commit/9f933d586654c04e734f7eb5455b6253c54ab5b7 CI was modified, and quotes for the ruby version `3.0` were removed/not added. But that actually causes it to resolve against the latest 3.X ruby (https://github.com/actions/runner/issues/849). Additionally, it removed testing against in-between Rubies. That seems a bit risky, so I added them back in one job at least so there are not too many extra checks being done.
Finally, test against Ruby 3.4
For more information on following Developer Certificate of …

Test against Ruby 3.4

---

CHANGELOG.md
UPGRADING.md
api_generator/lib/templates/api.mustache
guides/transport_options.md
lib/opensearch/api.rb
lib/opensearch/transport.rb
lib/opensearch/transport/transport/base.rb
lib/opensearch/transport/transport/serializer/json.rb
lib/opensearch/version.rb
opensearch-ruby.gemspec
spec/opensearch/api/api_spec.rb
spec/opensearch/api/utils_spec.rb
test/transport/unit/serializer_test.rb

Historically, the `json` gem that is default from ruby has been somewhat slow compared to other available implementations like the `oj` gem. Gems like `multi_json` exist to allow people to choose which backend they want to use. For example, to use `oj`, one has to simply add it to their gemfile and then use `MultiJson.load` and it will automatically use the `oj` gem.
Over the last few months there has been some great work to make the default `json` implementation in ruby more performant. In the following script, `json` used to be 1.5x times slower, now it is 1.4x times faster compared to `oj`:
<details><summary>Benchmark</summary>
<p>
```rb
require "bundler/inline"
gemfile do
source 'https://rubygems.org'
gem 'json'
gem 'multi_json'
gem 'oj'
gem 'benchmark-ips'
end
data = …
```

Change the default serializer to the `json` gem for 4.0.0-beta.5

---

.github/workflows/main.yml
.github/workflows/test-unreleased.yml
CHANGELOG.md
Gemfile
README.md
UPGRADING.md
lib/opensearch/transport/client.rb
opensearch-ruby.gemspec
spec/spec_helper.rb
test/transport/integration/transport_test.rb

Faraday 2 has been out for a few years now already. As discussed in https://github.com/opensearch-project/opensearch-ruby/pull/290#issuecomment-2832292922
None

Remove support for faraday 1.X

---

.github/workflows/compatibility.yml
.github/workflows/main.yml
.github/workflows/test-unreleased.yml

Add OpenSearch 3 to CI since it is now GA. I made a few commits, see their message for rationale for each.
Part of https://github.com/opensearch-project/opensearch-ruby/issues/294

Adapt CI for opensearch 3

---

lib/opensearch/api/utils.rb

In Ruby 3.5, most of the `cgi` gem is removed. Only methods relating to escaping/unescaping are retained.
Those are the only thing that's being used, so use the more specific require and avoid the warning that would otherwise be emitted. Doing it like this works since Ruby 2.4.
https://bugs.ruby-lang.org/issues/21258
None

Only require what is necessary from `cgi` for Ruby 3.5
